dist: focal
os: linux
language: php
php: '8.1.0'

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer require --dev php-coveralls/php-coveralls
  - composer install

# Run before the build
before_script:
  - mkdir -p build/logs # Create a folder to store clover files
  - mkdir -p /home/travis/cache

script:
  - php vendor/bin/phpunit -c phpunit.xml

# After success, run sh to bind coveralls
after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  slack:
    secure: d7dnnxI5RLf0ct25rTJXcXIadRqllxdOcwdnPvDb/HIYX2JI4DwO0PkeJn7GYfNIdQdpEh155mOOaMDt/Cb35REO8nK0T+sSfXCgrtag6VJU0H63nBXJmEhL6u5zHOglqfMVe+PD4jDr9hYoK1Ns+yFHD5LVJoFlyjyVsKrikwepX0372nFnkGOQYij4Dg63xKDSCqzgd1Y849k5l5myBEqiExtwhoKbpDouTh+QYLQ6z4g10TVLZ6dS5c+rQB+Y8ScCtqUjBA/837YNwKRlPaUqhY4A09wXNoNU4L+RuBWT93L7WOEzJLG26GRHPsuBpA8q+1Vi3TlxGTxdxHHzxeZz0XvMjlmEQZWJUxEVVJkYx8yI3hoLia0zgAjiIkPjLRm7g51sgwhKnX4RGGLs32RuRagfgPJbIN3mLqJtDfKKlhdxusKzqkpqUFTi6zAZiDhWhM8TpZpQlO8WT+vvjsgX+jgyY4M4RALERPSw1Z5aN2pKIkAbB1GNBWOvaIq1v5yrKCNp2ElQgrUZYhLr3NCP8I9DU0QpnYw+QzPuDES7YzETv89EDItYE+p9qM6kQa4fKJtkxd6WNb+aqaaTbq0YySBO/RtVeUsRQQqW/gw6pwhDieFsnwUl/aVzu+sOajFmcMFleFeQHOc6hSjCB5jYd0dp6i0e5h1a/Ht5+R0=