version: '3.7'

services:
  minimalism:
    container_name: minimalism_9
    image: carlonicora/minimalism:9.0.0
    working_dir: /app
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../:/app
      - ../:/opt/project
    tty: true
    stdin_open: true